# Generated by Django 4.1 on 2024-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_interest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
