# Generated by Django 4.1 on 2024-09-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_interest_app', '0004_memberofparliament_house_fk_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberofparliament',
            name='house',
        ),
    ]
