# Generated by Django 4.1 on 2024-09-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_interest_app', '0005_remove_memberofparliament_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberofparliament',
            old_name='house_fk',
            new_name='house',
        ),
    ]
