# Generated by Django 4.1 on 2024-11-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members_interest_app", "0007_alter_memberofparliament_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredInterest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("api_id", models.CharField(max_length=255)),
                (
                    "unique_api_generated_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("category_id", models.CharField(max_length=255)),
                ("category_name", models.CharField(max_length=255)),
                ("sort_order", models.CharField(max_length=255)),
                ("interest_summary", models.TextField(null=True)),
                ("date_created", models.DateTimeField()),
                ("date_last_amended", models.DateTimeField(null=True)),
                ("date_deleted", models.DateTimeField(blank=True, null=True)),
                ("is_correction", models.BooleanField(default=False)),
                ("is_child_interest", models.BooleanField(default=False)),
                (
                    "parent_interest",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "interest_currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GBP", "Pound Sterline"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("AUD", "Australian Dollar"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "number_of_extracted_amounts",
                    models.IntegerField(blank=True, null=True),
                ),
                ("contains_loan", models.BooleanField(blank=True, null=True)),
                ("contains_time_period", models.BooleanField(blank=True, null=True)),
                ("payer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("person", "person"),
                            ("company", "company"),
                            ("unknown", "unknown"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("payer_address", models.TextField(blank=True, null=True)),
                (
                    "payer_companies_house_id",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("purpose", models.TextField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "family_member_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "family_member_relationship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "family_member_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "family_member_paid_by_mp_or_parliament",
                    models.BooleanField(blank=True, null=True),
                ),
                ("family_member_lobbies", models.BooleanField(blank=True, null=True)),
                (
                    "member_of_parliament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members_interest_app.memberofparliament",
                        to_field="api_id",
                    ),
                ),
            ],
        ),
    ]
