# Generated by Django 4.1 on 2024-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members_interest_app", "0008_registeredinterest"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("currency", models.CharField(max_length=3)),
                ("rate_to_gbp", models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
    ]
