# Generated by Django 4.1 on 2024-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members_interest_app", "0009_exchangerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredinterest",
            name="gbp_interest_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Stores the sterling-equivalent value of the interest amount.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
